b0 = 100.0
alpha_R = 0.005
alpha_A = -0.010
alpha_Ap = -0.012
theta = 0.0285
a0 = 0.0
b_dt = 15.0
cK = 1.2
leadOuterDrift_1 = 0.034
outerBaseCost = 0.022
tau_k = 0.030
beta_sq = 0.006
beta_wk = 0.004
k_turn_err = 0.010
gamma_wall = 0.006
delta_first = 0.70
delta_lineblock = 0.5
safe_margin_mu = 0.005
safe_margin_sigma = 0.003
p_safe_margin = 0.20
p_backoff = 0.10
backoff_ST_shift = 0.015
backoff_A_penalty = 0.15
p_cav = 0.03
cav_A_penalty = 0.25
session_ST_shift_mu = 0.0
session_ST_shift_sd = 0.004
session_A_bias_mu = 0.0
session_A_bias_sd = 0.10
wind_theta_gain = 0.002
wind_st_sigma_gain = 0.5
base_wake = 0.20
extra_wake_when_outside = 0.25
decision_bias_mult = 1.0
