# params/ultra_stable.toml
b_dt = 10.0
cK = 1.35
decision_bias_mult = 0.85

p_safe_margin = 0.10
safe_margin_mu = 0.003
safe_margin_sigma = 0.002

session_ST_shift_sd = 0.002
session_A_bias_sd   = 0.05
k_turn_err = 0.006

base_wake = 0.12
beta_wk   = 0.002
extra_wake_when_outside = 0.18

delta_first = 0.40
delta_lineblock = 0.30

wind_theta_gain = 0.001
wind_st_sigma_gain = 0.3
