name: Crawl & Publish

on:
  workflow_dispatch:
    inputs:
      racers:
        description: "RACERS (例: 4349,3156) 空ならtodayの全出走者"
        required: false
        default: ""
      batch:
        description: "一度に処理する人数 (空=制限なし)"
        required: false
        default: ""
      delayMs:
        description: "1選手ごとの待機(ms) 例: 3000"
        required: false
        default: "3000"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install --no-audit --no-fund

      # 以降、pushはスクリプトが実施するのでcommitステップは不要
      - name: Configure git (for script-side push)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run crawler
        run: node scripts/crawl.js

      - name: Fetch racer stats & push
        env:
          RACERS: ${{ inputs.racers }}
          STATS_BATCH: ${{ inputs.batch }}
          STATS_DELAY_MS: ${{ inputs.delayMs }}
        run: node scripts/fetch-stats.js
