name: Crawl & Publish

on:
  # 手動実行
  workflow_dispatch:
    inputs:
      racers:
        description: "RACERS (例: 4349,3156) 空ならtodayの全出走者"
        required: false
        default: ""
      batch:
        description: "一度に処理する人数 (空=制限なし)"
        required: false
        default: ""
      delayMs:
        description: "1選手ごとの待機(ms) 例: 3000"
        required: false
        default: "3000"
  # 毎日 07:00 JST に自動実行（＝UTC 22:00）
  schedule:
    - cron: "0 22 * * *"

permissions:
  contents: write

concurrency:
  group: crawl-publish
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run crawler
        run: node scripts/crawl.js

      - name: Fetch racer stats
        env:
          # schedule では inputs が空なので、delay は '3000' にフォールバック
          RACERS: ${{ inputs.racers }}
          STATS_BATCH: ${{ inputs.batch }}
          STATS_DELAY_MS: ${{ inputs.delayMs || '3000' }}
        run: node scripts/fetch-stats.js

      - name: Build picks (score races)
        run: node scripts/score-race.js

      - name: Commit & Push changes
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update programs, stats and picks [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi