name: Crawl & Publish

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ここを追加：依存を入れる（lockfile無しでもOK）
      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run crawler
        run: node scripts/crawl.js

      - name: Fetch racer stats (boatrace-db)
        run: node scripts/fetch-stats.js

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet && echo "No changes" || (git commit -m "chore: publish data [skip ci]" && git push)
