name: Crawl & Publish

on:
  # 手動実行
  workflow_dispatch:
    inputs:
      racers:
        description: "RACERS (例: 4349,3156) 空ならtodayの全出走者"
        required: false
        default: ""
      batch:
        description: "一度に処理する人数 (空=制限なし)"
        required: false
        default: ""
      delayMs:
        description: "1選手ごとの待機(ms)"
        required: false
        default: "3000"
  # 毎朝 05:00 JST（= 前日 20:00 UTC）
  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write

concurrency:
  group: crawl-publish
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # 念のため
          git config pull.rebase true

      - name: Run crawler
        run: node scripts/crawl.js

      - name: Fetch racer stats
        env:
          RACERS: ${{ inputs.racers }}
          STATS_BATCH: ${{ inputs.batch }}
          STATS_DELAY_MS: ${{ inputs.delayMs || '3000' }}
        run: node scripts/fetch-stats.js

      - name: Commit & Push changes (with rebase & retry)
        run: |
          set -e
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update racer stats [skip ci]"

          # push→reject 対策でリトライ (最大5回)
          n=0
          until [ $n -ge 5 ]
          do
            if git push; then
              echo "Pushed successfully."
              exit 0
            fi
            echo "Push rejected. Rebasing onto remote and retrying... ($((n+1))/5)"
            # 最新取り込み（作業ツリーに変更があっても安全に）
            git pull --rebase --autostash
            n=$((n+1))
            sleep 2
          done

          echo "ERROR: Failed to push after retries."
          exit 1
