name: Crawl & Publish (slim from public JSON)

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD or today"
        required: false
        default: "today"
      pid:
        description: "Stadium code (01..24) or name"
        required: false
        default: "02"
      race:
        description: "Race number (1..12 or 1R..12R)"
        required: false
        default: "1"
  schedule:
    - cron: "0 21 * * *"   # JST 06:00

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i

      # health.json も毎回作る（任意）
      - name: Create health.json
        run: |
          mkdir -p public
          echo '{"ok":true,"ts":"'"$(date -u +%FT%TZ)"'"}' > public/health.json

      - name: Build one race JSON
        env:
          TARGET_DATE: ${{ github.event.inputs.date }}
          TARGET_PID:  ${{ github.event.inputs.pid }}
          TARGET_RACE: ${{ github.event.inputs.race }}
        run: npm run crawl

      - name: List outputs
        run: |
          echo "=== GENERATED FILES ==="
          ls -R public || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
