name: Test Exhibition Direct (Full Auto)

on:
  workflow_dispatch:
    inputs:
      date:
        description: "上書き用: YYYYMMDD（未指定ならJST今日）"
        required: false
      pids:
        description: "場コード（カンマ区切り / 例: 01,04,24）。未指定は 全場"
        required: false
      force:
        description: "時間帯外でも実行するなら 1"
        required: false
  schedule:
    - cron: "*/1 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      - name: Compute JST window
        shell: bash
        run: |
          HM=$((10#$(TZ=Asia/Tokyo date +'%H%M')))
          DEF_DATE=$(TZ=Asia/Tokyo date +'%Y%m%d')
          IN_WINDOW=false
          if [ $HM -ge 730 ] && [ $HM -le 2200 ]; then IN_WINDOW=true; fi
          echo "JST_NOW=$(TZ=Asia/Tokyo date +'%Y-%m-%d %H:%M:%S')" | tee -a $GITHUB_ENV
          echo "IN_WINDOW=$IN_WINDOW" | tee -a $GITHUB_ENV
          echo "DEF_DATE=$DEF_DATE"   | tee -a $GITHUB_ENV
          echo "PIDS=${{ inputs.pids || '01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24' }}" | tee -a $GITHUB_ENV

      - name: Early exit when out of window
        if: ${{ !inputs.force && env.IN_WINDOW != 'true' }}
        run: |
          echo "Out of window (JST 07:30–22:00 以外)。終了します。"
          exit 0

      - name: Resolve inputs (DATE / PIDS / RACES mode)
        shell: bash
        run: |
          DATE="${{ inputs.date }}"
          if [ -z "$DATE" ]; then DATE="$DEF_DATE"; fi
          echo "DATE=$DATE" | tee -a $GITHUB_ENV
          echo "Resolved: DATE=$DATE PIDS=$PIDS RACES=AUTO_T15"

      - name: Run direct exhibition crawler (AUTO_T15)
        shell: bash
        run: |
          node scripts/fetch-exhibition-direct.js "$DATE" "$PIDS" auto --skip-existing

      - name: Commit & push results
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "exhibition direct(auto): $DATE $PIDS [skip ci]"
            git pull --rebase
            git push
          else
            echo "No changes."
          fi
