# .github/workflows/exhibition-direct.yml
name: Test Exhibition Direct

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD（例: 20250809）"
        required: true
        default: ""
      pid:
        description: "場コード 01..24（例: 02）"
        required: true
        default: "02"
      race:
        description: "レース番号（例: 5R または 5）"
        required: true
        default: "1R"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      # デバッグ（入力確認）
      - name: Echo inputs
        run: |
          echo "date=${{ inputs.date }}"
          echo "pid=${{ inputs.pid }}"
          echo "race=${{ inputs.race }}"

      # 展示後 直接クロール（CLI 引数で渡す）
      - name: Run direct exhibition crawler
        run: |
          set -euo pipefail
          DATE="${{ inputs.date }}"
          PID="${{ inputs.pid }}"
          IN_RACE="${{ inputs.race }}"
          # race を 1..12 / 1R..12R どちらでも受け取れるように正規化
          RACE="$(echo "$IN_RACE" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g; s/[Rr]$//')"
          if ! [[ "$RACE" =~ ^([1-9]|1[0-2])$ ]]; then
            echo "race の形式が不正です: $IN_RACE" >&2
            exit 1
          fi
          RACE="${RACE}R"

          echo "-> exec: node scripts/fetch-exhibition-direct.js $DATE $PID $RACE"
          node scripts/fetch-exhibition-direct.js "$DATE" "$PID" "$RACE" --skip-existing

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "exhibition direct: ${{ inputs.date }} ${{ inputs.pid }} ${{ inputs.race }} [skip ci]"
            git pull --rebase
            git push
          else
            echo "No changes."
          fi
