# .github/workflows/exhibition-direct.yml
name: Test Exhibition Direct

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD（例: 20250809）"
        required: true
        default: ""
      pid:
        description: "場コード 01..24（例: 02）"
        required: true
        default: "02"
      race:
        description: "レース番号（例: 5R または 5）"
        required: true
        default: "1R"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      # 入力が正しく取れているかログで確認
      - name: Echo inputs
        run: |
          echo "date=${{ inputs.date }}"
          echo "pid=${{ inputs.pid }}"
          echo "race=${{ inputs.race }}"

      - name: Run direct exhibition crawler
        run: |
          node scripts/fetch-exhibition-direct.js \
            "${{ inputs.date }}" \
            "${{ inputs.pid }}" \
            "${{ inputs.race }}"

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "exhibition direct: ${{ inputs.date }} ${{ inputs.pid }} ${{ inputs.race }} [skip ci]"
            git pull --rebase
            git push
          else
            echo "No changes."
          fi
