name: Build Exhibitions

on:
  schedule:
    # 毎日07:00〜22:00 JST (日本時間) 1分間隔
    # JST=UTC+9 なので、UTCでは前日22:00〜当日13:00
    - cron: "* 22-23 * * *"  # 前日22時〜23時UTC = 当日07時〜08時JST
    - cron: "* 0-12 * * *"   # 当日09時〜22時JST

  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD or today"
        required: true
        default: "today"
      pids:
        description: "場コードCSV (例: 02,09)"
        required: false
        default: "02"
      races:
        description: "レースCSV (例: 1R,2R または 1,2) 空=1..12"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run exhibition builder (skip if already exists)
        env:
          TARGET_DATE:  ${{ inputs.date || 'today' }}
          TARGET_PIDS:  ${{ inputs.pids || '02' }}
          TARGET_RACES: ${{ inputs.races || '' }}
        run: node scripts/fetch-exhibition.js --skip-existing

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update exhibition data [skip ci]"
            git pull --rebase
            git push
          else
            echo "No exhibition changes."
          fi
