name: Integrate and Publish

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD or 'today' (JST)"
        required: true
        default: "today"
      pid:
        description: "01..24"
        required: true
        default: "04"
      race:
        description: "1R..12R"
        required: true
        default: "1R"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      - name: Resolve params (JST 'today')
        id: p
        shell: bash
        run: |
          DATE_IN='${{ inputs.date }}'
          if [ "$DATE_IN" = "today" ]; then
            DATE_IN=$(TZ=Asia/Tokyo date +%Y%m%d)
          fi
          PID=$(printf '%02d\n' $((10#${{ inputs.pid }})))
          RACE=$(echo '${{ inputs.race }}' | tr '[:lower:]' '[:upper:]')
          echo "date=$DATE_IN"  >> $GITHUB_OUTPUT
          echo "pid=$PID"       >> $GITHUB_OUTPUT
          echo "race=$RACE"     >> $GITHUB_OUTPUT
          echo "Resolved: DATE=$DATE_IN PID=$PID RACE=$RACE"

      - name: Integrate once
        env:
          DATE: ${{ steps.p.outputs.date }}
          PID:  ${{ steps.p.outputs.pid }}
          RACE: ${{ steps.p.outputs.race }}
        run: |
          node scripts/integrate-once.mjs --date "$DATE" --pid "$PID" --race "$RACE"
          echo "=== listing ==="
          ls -la "public/integrated/v1/$DATE/$PID" || true

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "integrated: ${{ steps.p.outputs.date }} ${{ steps.p.outputs.pid }} ${{ steps.p.outputs.race }} [skip ci]"
            git pull --rebase
            git push
          else
            echo "No changes."
          fi
