name: Integrate and Publish All

on:
  schedule:
    # 2分ごとに起動
    - cron: "*/2 * * * *"
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD or 'today' (JST)"
        required: true
        default: "today"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      - name: Resolve date (JST)
        id: params
        shell: bash
        run: |
          set -euo pipefail
          DATE_IN="${{ inputs.date }}"
          if [ -z "$DATE_IN" ] || [ "$DATE_IN" = "today" ]; then
            DATE=$(TZ=Asia/Tokyo date +'%Y%m%d')
          else
            DATE="${DATE_IN//-/}"
          fi
          echo "DATE=$DATE" | tee -a $GITHUB_ENV
          echo "Resolved DATE=$DATE"

      - name: Loop all venues & races
        shell: bash
        run: |
          set -euo pipefail
          DATE="$DATE"
          STATS_DIR="public/stats/v2/racers"

          VENUES=$(seq -w 1 24)
          RACES=$(seq 1 12 | sed 's/$/R/')

          for PID in $VENUES; do
            for RACE in $RACES; do
              PROG="public/programs/v2/$DATE/$PID/$RACE.json"
              EXH="public/exhibition/v1/$DATE/$PID/$RACE.json"
              OUT="public/integrated/v1/$DATE/$PID/$RACE.json"

              # 既に統合済ならスキップ
              if [ -f "$OUT" ]; then
                echo "[$PID $RACE] already integrated, skip"
                continue
              fi

              # 2ソース存在チェック
              if [ ! -f "$PROG" ] || [ ! -f "$EXH" ]; then
                echo "[$PID $RACE] missing program or exhibition, skip"
                continue
              fi

              # stats全員分存在チェック
              node -e "
                const fs=require('fs');
                const progPath='$PROG';
                const statsDir='$STATS_DIR';
                let ok=true;
                try {
                  const j=JSON.parse(fs.readFileSync(progPath,'utf8'));
                  const entries=(j.entries||j.boats||[]);
                  for(const e of entries){
                    const n=Number(e.number ?? e.racer_number ?? e.id);
                    if(!n) continue;
                    const f=\`\${statsDir}/\${n}.json\`;
                    if(!fs.existsSync(f)){ ok=false; break; }
                  }
                } catch(err) { ok=false; }
                process.exit(ok?0:2);
              " || { echo "[$PID $RACE] missing stats, skip"; continue; }

              # 実行
              echo "[$PID $RACE] integrating..."
              node scripts/integrate-once.mjs --date "$DATE" --pid "$PID" --race "$RACE"
            done
          done

      - name: Commit & push
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "auto integrate all: $DATE [skip ci]"
            git pull --rebase
            git push
          else
            echo "No changes."
          fi
