# .github/workflows/log-feedback.yml
name: Log Feedback

on:
  workflow_dispatch:
    inputs:
      note:
        description: "メモ（補正ルール・所感）"
        required: true

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Update heuristics notes
        env:
          NOTE: ${{ inputs.note }}
        run: node scripts/update-rules.mjs

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "heuristics: note added [skip ci]"
            git pull --rebase --autostash || true
            git push
          else
            echo "No changes."
          fi
