name: Manual Integrate Test

on:
  workflow_dispatch:
    inputs:
      date:
        description: "開催日 YYYYMMDD（例: 20250810 or today）"
        required: true
        default: "today"
      pid:
        description: "場コード 01..24（例: 04）"
        required: true
        default: "04"
      race:
        description: "レース番号 1R..12R（例: 1R）"
        required: true
        default: "1R"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci
          npm i -D wait-on

      - name: Start API (background)
        env:
          PORT: 3000
        run: |
          node server.js & echo $! > server.pid
          npx wait-on http://127.0.0.1:3000

      - name: Hit integrate endpoint
        env:
          DATE: ${{ github.event.inputs.date }}
          PID:  ${{ github.event.inputs.pid }}
          RACE: ${{ github.event.inputs.race }}
        run: |
          echo "Request: ${DATE}/${PID}/${RACE}"
          curl -sS "http://127.0.0.1:3000/api/integrate/v1/${DATE}/${PID}/${RACE}" -o response.json
          echo "=== API response (first 2000 chars) ==="
          head -c 2000 response.json || true
          echo
          # 念のため生成先を確認
          ls -la public/integrated/v1 || true
          find public/integrated/v1 -type f -maxdepth 3 || true

      - name: Stop API
        if: always()
        run: |
          kill $(cat server.pid) || true

      - name: Upload integrated JSON
        uses: actions/upload-artifact@v4
        with:
          name: integrated-json
          path: |
            public/integrated/v1/**/*.json
            response.json
          if-no-files-found: warn
