name: schedules_v1

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD（空なら全日付スキャン）"
        required: false
  schedule:
    - cron: "00 22 * * *"  # JST 07:00 相当（UTC22:00）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build by date or scan all under programs/v2
        run: |
          python -m pip install -U pip
          # 依存なし（標準lib）だが将来の拡張のためpipは更新だけ
          if [ -z "${{ github.event.inputs.date }}" ]; then
            python scripts/schedules_build_all.py
          else
            python scripts/schedules_build.py --date "${{ github.event.inputs.date }}"
          fi
      - name: Commit & push
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add public/schedules/v1/
          git commit -m "schedules_v1 build" || echo "no changes"
          git push
