name: Sims Integrated

on:
  workflow_dispatch:
    inputs:
      date:
        description: "日付 YYYYMMDD（空=今日）"
        required: false
        default: ""
      mode:
        description: "predict or eval"
        required: true
        default: "predict"
      pid:
        description: "場コード（カンマ区切り / 空=全場）"
        required: false
        default: ""
      races:
        description: "レース番号（カンマ区切り / 空=全レース）"
        required: false
        default: ""
      sims:
        description: "試行回数"
        required: false
        default: "5000"
      topn:
        description: "上位N"
        required: false
        default: "18"
      options:
        description: "追加オプション（YAML形式）"
        required: false
        default: |
          filters:
            require_odds: false
            min_ev: 0
            odds_bands: ""
            odds_min: 0
            odds_max: 0
            exclude_first1: false
            only_first1: false
            buy_in_top3: false
            buy_thr: 0.7
          keyman:
            enable: true
            threshold: 0.7
            boost: 0.15
            aggr: 0.0
            buy_in_top3: false
            buy_thr: 0.7

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run Sims Integrated
        run: |
          python scripts/sims_integrated.py \
            --date "${{ github.event.inputs.date }}" \
            --mode "${{ github.event.inputs.mode }}" \
            --pid "${{ github.event.inputs.pid }}" \
            --races "${{ github.event.inputs.races }}" \
            --sims "${{ github.event.inputs.sims }}" \
            --topn "${{ github.event.inputs.topn }}" \
            --options '${{ github.event.inputs.options }}'

      - name: Commit results into repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "update sims results" || echo "No changes"
          git push
