name: SimS v1 Runner (unified)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "predict or eval"
        required: true
        default: predict
      dates:
        description: "YYYYMMDDをカンマ区切り"
        required: true
      pids:
        description: "場コード(空=全場)"
        default: ""
      races:
        description: "レース(空=全レース)"
        default: ""
      sims:
        description: "試行回数（predict/eval共通）"
        default: "1200"
      topn:
        description: "上位N（predict/eval共通）"
        default: "18"
      unit:
        description: "均等購入額（eval用）"
        default: "100"
      limit:
        description: "先頭からNレースだけ処理（0なら全件）"
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    # ← これを追加：push するための権限
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # Actions トークンで push 可

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install numpy pandas

      - name: Clean output dirs
        run: |
          rm -rf ./predict ./out
          mkdir -p ./predict ./out

      # ---- predict: TOPNのみを ./predict に出力（毎回上書き） ----
      - name: Predict (TOPN, same engine as eval)
        if: ${{ github.event.inputs.mode == 'predict' }}
        run: |
          python sims_batch_eval_SimS_v1.py \
            --base ./public \
            --dates "${{ github.event.inputs.dates }}" \
            --sims  "${{ github.event.inputs.sims }}" \
            --topn  "${{ github.event.inputs.topn }}" \
            --pids  "${{ github.event.inputs.pids }}" \
            --races "${{ github.event.inputs.races }}" \
            --limit "${{ github.event.inputs.limit }}" \
            --predict-only

      # ★ 追加：predict をリポジトリにコミット & プッシュ
      - name: Commit predict folder to repo
        if: ${{ github.event.inputs.mode == 'predict' }}
        run: |
          set -e
          if [ -z "$(ls -A ./predict)" ]; then
            echo "predict/ is empty. Nothing to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # 既存ファイルはそのまま上書きコミット
          git add -A predict
          git commit -m "chore(predict): ${{
            github.event.inputs.dates }} ${{
            github.event.inputs.pids }} ${{
            github.event.inputs.races }} (topN=${{ github.event.inputs.topn }}, sims=${{ github.event.inputs.sims }})" || echo "No changes to commit"
          git push

      - name: Upload predict artifact
        if: ${{ github.event.inputs.mode == 'predict' }}
        uses: actions/upload-artifact@v4
        with:
          name: sims_outputs
          path: ./predict
          if-no-files-found: error

      # ---- eval: ROI集計を ./out に出力 ----
      - name: Eval (ROI)
        if: ${{ github.event.inputs.mode == 'eval' }}
        run: |
          python sims_batch_eval_SimS_v1.py \
            --base ./public \
            --dates "${{ github.event.inputs.dates }}" \
            --sims  "${{ github.event.inputs.sims }}" \
            --topn  "${{ github.event.inputs.topn }}" \
            --unit  "${{ github.event.inputs.unit }}" \
            --limit "${{ github.event.inputs.limit }}" \
            --outdir ./out

      - name: Upload eval artifact
        if: ${{ github.event.inputs.mode == 'eval' }}
        uses: actions/upload-artifact@v4
        with:
          name: sims_outputs
          path: ./out
          if-no-files-found: error