name: SimS Unified Pipeline

on:
  workflow_dispatch:
    inputs:
      date:
        description: '予測日 (例: 20250820)'
        required: true
      pids:
        description: '場コード (例: 01,04)'
        required: false
        default: ''
      races:
        description: 'レース番号 (例: 1R,2R)'
        required: false
        default: ''
      sims:
        description: '試行回数'
        required: false
        default: '1200'
      topn:
        description: '上位N件出力'
        required: false
        default: '18'
      limit:
        description: '先頭からNレースだけ処理 (0=全件)'
        required: false
        default: '0'

jobs:
  pass3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run pass3 for all PIDs
        run: |
          IFS=',' read -ra PID_ARR <<< "${{ github.event.inputs.pids }}"
          for PID in "${PID_ARR[@]}"; do
            echo "Launching wf_pass3_sims_integrated for PID=$PID"
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/wf_pass3_sims_integrated.yml/dispatches \
              -d "$(jq -n \
                --arg ref "${{ github.ref }}" \
                --arg date "${{ github.event.inputs.date }}" \
                --arg mode "predict" \
                --arg unit "default" \
                --arg sims "${{ github.event.inputs.sims }}" \
                --arg topn "${{ github.event.inputs.topn }}" \
                --arg pids "$PID" \
                --arg races "${{ github.event.inputs.races }}" \
                --arg limit "${{ github.event.inputs.limit }}" \
                '{ref: $ref, inputs: {date: $date, mode: $mode, unit: $unit, sims: $sims, topn: $topn, pids: $pids, races: $races, limit: $limit}}')"
          done
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
