name: SimS Pipeline

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD（空=JSTの今日）"
        required: false
        default: ""
      pids:
        description: "場コード（カンマ区切り / 例: 01,04,24）"
        required: false
        default: ""
      races:
        description: "レース（カンマ区切り / 例: 1R,2R）"
        required: false
        default: ""
      sims:
        description: "試行回数（predict）"
        required: false
        default: "600"
      topn:
        description: "上位N（三連単）"
        required: false
        default: "18"
      unit:
        description: "1点あたり（円）"
        required: false
        default: "100"
      filters:
        description: "例: require_odds=true,min_ev=1.2,odds_bands=01-09,10-19"
        required: false
        default: ""
      keyman:
        description: "例: enable=true,thr=0.7,boost=0.15,aggr=0.0,buy_in_top3=false,buy_thr=0.7"
        required: false
        default: "enable=true,thr=0.7,boost=0.15,aggr=0.0,buy_in_top3=false,buy_thr=0.7"

jobs:
  pass3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pid: ${{ fromJson(inputs.pids != '' && '[' + inputs.pids + ']' || '["01"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call pass3 (SimS integrated)
        uses: ./.github/workflows/wf_pass3_sims_integrated.yml
        with:
          DATE: ${{ inputs.date }}
          PID: ${{ matrix.pid }}
          MODE: predict
          SIMS: ${{ inputs.sims }}
          TOPN: ${{ inputs.topn }}
          UNIT: ${{ inputs.unit }}
          FILTERS: ${{ inputs.filters }}
          KEYMAN: ${{ inputs.keyman }}
          OUTDIR: scripts/sims
