name: SimS v1 Runner (unified)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "predict or eval"
        required: true
        default: predict
      dates:
        description: "YYYYMMDDをカンマ区切り"
        required: true
      pids:
        description: "場コード(空=全場)"
        default: ""
      races:
        description: "レース(空=全レース)"
        default: ""
      sims:
        description: "試行回数（predict/eval共通）"
        default: "1200"
      topn:
        description: "上位N（predict/eval共通）"
        default: "18"
      unit:
        description: "均等購入額（eval用）"
        default: "100"
      limit:
        description: "先頭からNレースだけ処理（0なら全件）"
        default: "0"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas

      - name: Clean output dirs
        run: |
          rm -rf ./predict ./out
          mkdir -p ./predict ./out

      # ---- predict: TOPNのみを ./predict に出力（毎回上書き） ----
      - name: Predict (TOPN, same engine as eval)
        if: ${{ github.event.inputs.mode == 'predict' }}
        run: |
          python sims_batch_eval_SimS_v1.py \
            --base ./public \
            --dates "${{ github.event.inputs.dates }}" \
            --sims  "${{ github.event.inputs.sims }}" \
            --topn  "${{ github.event.inputs.topn }}" \
            --pids  "${{ github.event.inputs.pids }}" \
            --races "${{ github.event.inputs.races }}" \
            --limit "${{ github.event.inputs.limit }}" \
            --predict-only

      - name: Show predict outputs
        if: ${{ github.event.inputs.mode == 'predict' }}
        run: |
          echo "=== tree ./predict ==="
          ls -lahR ./predict || true
          echo "=== head predictions_summary.csv (if exists) ==="
          [ -f ./predict/predictions_summary.csv ] && head -n 20 ./predict/predictions_summary.csv || echo "no predictions_summary.csv"
          echo "=== _EMPTY.txt (if exists) ==="
          [ -f ./predict/_EMPTY.txt ] && cat ./predict/_EMPTY.txt || echo "no _EMPTY.txt"

      - name: Upload predict artifact
        if: ${{ github.event.inputs.mode == 'predict' }}
        uses: actions/upload-artifact@v4
        with:
          name: sims_outputs_predict_${{ github.event.inputs.dates }}
          path: ./predict
          if-no-files-found: error

      # ---- eval: ROI集計を ./out に出力 ----
      - name: Eval (ROI)
        if: ${{ github.event.inputs.mode == 'eval' }}
        run: |
          python sims_batch_eval_SimS_v1.py \
            --base ./public \
            --dates "${{ github.event.inputs.dates }}" \
            --sims  "${{ github.event.inputs.sims }}" \
            --topn  "${{ github.event.inputs.topn }}" \
            --unit  "${{ github.event.inputs.unit }}" \
            --limit "${{ github.event.inputs.limit }}" \
            --outdir ./out

      - name: Show eval outputs
        if: ${{ github.event.inputs.mode == 'eval' }}
        run: |
          echo "=== tree ./out ==="
          ls -lahR ./out || true
          echo "=== overall.json (if exists) ==="
          [ -f ./out/overall.json ] && cat ./out/overall.json || echo "no overall.json"
          echo "=== head per_race_results.csv (if exists) ==="
          [ -f ./out/per_race_results.csv ] && head -n 20 ./out/per_race_results.csv || echo "no per_race_results.csv"

      - name: Upload eval artifact
        if: ${{ github.event.inputs.mode == 'eval' }}
        uses: actions/upload-artifact@v4
        with:
          name: sims_outputs_eval_${{ github.event.inputs.dates }}
          path: ./out
          if-no-files-found: error
