      - name: Run SimS
        working-directory: scripts/sims
        shell: bash
        run: |
          set -euo pipefail

          # inputs → 変数
          BASE_INPUT="${{ inputs.base }}"
          DATES="${{ inputs.dates }}"
          SIMS="${{ inputs.sims || '600' }}"
          TOPN="${{ inputs.topn || '18' }}"
          UNIT="${{ inputs.unit || '100' }}"
          STRATEGY="${{ inputs.strategy || 'trifecta_topN' }}"
          KVAL="${{ inputs.k || '2' }}"
          MVAL="${{ inputs.m || '4' }}"
          PIDS="${{ inputs.pids }}"
          RACES="${{ inputs.races }}"

          # base が空なら、scripts/sims から見た public を既定に
          if [ -z "$BASE_INPUT" ]; then
            BASE="../../public"
          else
            BASE="$BASE_INPUT"
          fi

          echo "[debug] CWD=$(pwd)"
          echo "[debug] BASE=$BASE"
          ls -la "$BASE" || { echo "[error] BASE not found"; exit 1; }

          # 安全な引数構築（配列）
          ARGS=( --base "$BASE" --sims "$SIMS" --unit "$UNIT" )

          [ -n "$DATES" ] && ARGS+=( --dates "$DATES" )
          [ -n "$PIDS"  ] && ARGS+=( --pids "$PIDS" )
          [ -n "$RACES" ] && ARGS+=( --races "$RACES" )

          if [ "$STRATEGY" = "exacta_topK_third_topM" ]; then
            ARGS+=( --strategy exacta_topK_third_topM --k "$KVAL" --m "$MVAL" )
          else
            ARGS+=( --strategy trifecta_topN --topn "$TOPN" )
          fi

          # 直下に出力
          OUTDIR="."
          echo "[debug] args: ${ARGS[*]}"

          python sims.py "${ARGS[@]}" --outdir "$OUTDIR"
