name: sims_pipeline

on:
  workflow_dispatch:
    inputs:
      DATE:
        description: "日付 (例: 20250820)"
        required: true
        type: string
      PIDS:
        description: "場コード（例: 01,02,...）"
        required: true
        type: string
      SIMS:
        description: "試行回数（例: 600）"
        required: false
        default: "600"
        type: string
      TOPN:
        description: "三連単 TopN（例: 18）"
        required: false
        default: "18"
        type: string
      UNIT:
        description: "1点あたりの金額（例: 100）"
        required: false
        default: "100"
        type: string
      MODE:
        description: "モード（predict または eval）"
        required: true
        default: "predict"
        type: string
      FILTERS:
        description: "フィルター文字列"
        required: false
        default: ""
        type: string
      KEYMAN:
        description: "キーマンパラメータ"
        required: false
        default: ""
        type: string
      OUTDIR:
        description: "出力ディレクトリ"
        required: false
        default: "scripts/sims"
        type: string

jobs:
  pass3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pass3 for all PIDs
        env:
          DATE: ${{ inputs.DATE }}
          PIDS: ${{ inputs.PIDS }}
          SIMS: ${{ inputs.SIMS }}
          TOPN: ${{ inputs.TOPN }}
          UNIT: ${{ inputs.UNIT }}
          MODE: ${{ inputs.MODE }}
          FILTERS: ${{ inputs.FILTERS }}
          KEYMAN: ${{ inputs.KEYMAN }}
          OUTDIR: ${{ inputs.OUTDIR }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          IFS=',' read -ra PID_ARR <<< "$PIDS"

          for PID in "${PID_ARR[@]}"; do
            echo "Launching wf_pass3_sims_integrated for PID=$PID"

            gh workflow run wf_pass3_sims_integrated.yml \
              --ref main \
              -f DATE="$DATE" \
              -f PID="$PID" \
              -f MODE="$MODE" \
              -f SIMS="$SIMS" \
              -f TOPN="$TOPN" \
              -f UNIT="$UNIT" \
              -f FILTERS="$FILTERS" \
              -f KEYMAN="$KEYMAN" \
              -f OUTDIR="$OUTDIR"
          done
