name: SimS Pipeline

on:
  workflow_dispatch:
    inputs:
      DATE:
        description: "対象日付 (YYYYMMDD)"
        required: true
        type: string
      PIDS:
        description: "場コード（例: 01,02。空欄=全場）"
        required: false
        type: string
        default: ""
      RACES:
        description: "レース番号（例: 1R,2R。空欄=全レース）"
        required: false
        type: string
        default: ""
      SIMS:
        description: "シミュレーション回数"
        required: false
        type: string
        default: "1200"
      TOPN:
        description: "上位N件"
        required: false
        type: string
        default: "18"
      LIMIT:
        description: "最大レース件数（0=全件）"
        required: false
        type: string
        default: "0"
      F_REQUIRE_ODDS:
        description: "オッズ必須か？（true/false）"
        required: false
        type: string
        default: "false"
      F_MIN_EV:
        description: "最小EVフィルター値（0=フィルタ無効）"
        required: false
        type: string
        default: "0"

permissions:
  contents: write

jobs:
  run-pass3-pipeline:
    uses: boat-satan/racecard-crawl-api/.github/workflows/wf_pass3_sims_integrated.yml@main
    with:
      DATE: ${{ inputs.DATE }}
      PIDS: ${{ inputs.PIDS }}
      RACES: ${{ inputs.RACES }}
      SIMS: ${{ inputs.SIMS }}
      TOPN: ${{ inputs.TOPN }}
      LIMIT: ${{ inputs.LIMIT }}
      F_REQUIRE_ODDS: ${{ inputs.F_REQUIRE_ODDS }}
      F_MIN_EV: ${{ inputs.F_MIN_EV }}
    secrets: inherit
