name: Run SimS

on:
  workflow_dispatch:
    inputs:
      base:      { description: "Path to public (repo rootからの相対 or 絶対)", required: false, default: "" }
      dates:     { description: "YYYYMMDD(カンマ区切り)", required: false, default: "" }
      sims:      { description: "Sims per race", required: false, default: "600" }
      topn:      { description: "TopN (trifecta_topN時)", required: false, default: "18" }
      unit:      { description: "Bet unit (JPY)", required: false, default: "100" }
      filter:
        description: >-
          例: pids=02,04;races=1R,2R;only_first1=true;odds_base=./public/odds/v1;
              odds_bands=01-09,10-19,20-49;odds_min=10;odds_max=49;min_ev=1.2;require_odds=true;predict_only=false
        required: false
        default: ""
      exclude_first1:
        description: "1着=1号艇の買い目を除外（true/false）"
        required: false
        default: "false"
      params_name:
        description: "外部パラメータのファイル名のみ（例: freer-10.toml）※固定パス scripts/sims/params/ 配下を参照"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Tokyo
      PYTHON_SCRIPT: scripts/sims/sims.py

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install numpy pandas
          fi

      - name: Run SimS
        shell: bash
        run: |
          set -euo pipefail

          BASE_INPUT="${{ github.event.inputs.base || '' }}"
          DATES="${{ github.event.inputs.dates || '' }}"
          SIMS="${{ github.event.inputs.sims || '600' }}"
          TOPN="${{ github.event.inputs.topn || '18' }}"
          UNIT="${{ github.event.inputs.unit || '100' }}"
          FILTER="${{ github.event.inputs.filter || '' }}"
          EXCL="${{ github.event.inputs.exclude_first1 || 'false' }}"
          PARAMS_NAME="${{ github.event.inputs.params_name || '' }}"

          # repo 直下 public をデフォルトに
          BASE="${BASE_INPUT:-public}"

          # filter のパース
          PIDS=""; RACES=""
          ONLY="false"; ODDS_BASE=""
          MIN_EV=""
          REQUIRE_ODDS="false"
          ODDS_BANDS=""
          ODDS_MIN=""
          ODDS_MAX=""
          PREDICT_ONLY="false"

          if [ -n "$FILTER" ]; then
            IFS=';' read -r -a parts <<< "$FILTER"
            for kv in "${parts[@]}"; do
              key="$(echo "${kv%%=*}" | tr '[:upper:]' '[:lower:]')"
              val="${kv#*=}"
              case "$key" in
                pids)           PIDS="$val" ;;
                races)          RACES="$val" ;;
                only_first1)    ONLY="$val" ;;
                odds_base)      ODDS_BASE="$val" ;;
                min_ev)         MIN_EV="$val" ;;
                require_odds)   REQUIRE_ODDS="$val" ;;
                odds_bands)     ODDS_BANDS="$val" ;;
                odds_min)       ODDS_MIN="$val" ;;
                odds_max)       ODDS_MAX="$val" ;;
                predict_only)   PREDICT_ONLY="$val" ;;
              esac
            done
          fi

          # デフォルトのオッズディレクトリ（未指定時）
          if [ -z "$ODDS_BASE" ]; then
            ODDS_BASE="$BASE/odds/v1"
          fi

          # 排他チェック
          if [ "${EXCL,,}" = "true" ] && [ "${ONLY,,}" = "true" ]; then
            echo "::error ::exclude_first1 と only_first1 は同時指定できません"
            exit 1
          fi

          # ★ 固定プレフィックス: scripts/sims/params/ + <ファイル名>
          PARAMS_FILE=""
          if [ -n "$PARAMS_NAME" ]; then
            PARAMS_FILE="scripts/sims/params/$PARAMS_NAME"
            if [ ! -f "$PARAMS_FILE" ]; then
              echo "::error ::params file not found: $PARAMS_FILE"
              exit 1
            fi
          fi

          echo "[debug] BASE=$BASE"
          echo "[debug] DATES=${DATES:-'(none)'}"
          echo "[debug] TOPN=$TOPN  SIMS=$SIMS  UNIT=$UNIT"
          echo "[debug] ODDS_BASE=$ODDS_BASE  MIN_EV=${MIN_EV:-'(none)'}  REQUIRE_ODDS=$REQUIRE_ODDS"
          echo "[debug] ODDS_BANDS=${ODDS_BANDS:-'(none)'}  ODDS_MIN=${ODDS_MIN:-'(none)'}  ODDS_MAX=${ODDS_MAX:-'(none)'}"
          echo "[debug] ONLY_FIRST1=$ONLY  EXCLUDE_FIRST1=$EXCL  PREDICT_ONLY=$PREDICT_ONLY"
          echo "[debug] PARAMS_FILE=${PARAMS_FILE:-'(none)'}"
          [ -d "$BASE" ] && ls -la "$BASE" || true

          ARGS=( --base "$BASE" --sims "$SIMS" --unit "$UNIT" --strategy trifecta_topN --topn "$TOPN" )
          [ -n "$DATES" ] && ARGS+=( --dates "$DATES" )
          [ -n "$PIDS"  ] && ARGS+=( --pids "$PIDS" )
          [ -n "$RACES" ] && ARGS+=( --races "$RACES" )
          if [ "${EXCL,,}" = "true" ]; then ARGS+=( --exclude-first1 ); fi
          if [ "${ONLY,,}" = "true" ]; then ARGS+=( --only-first1 ); fi
          if [ "${PREDICT_ONLY,,}" = "true" ]; then ARGS+=( --predict-only ); fi
          [ -n "$ODDS_BASE" ] && ARGS+=( --odds-base "$ODDS_BASE" )
          [ -n "$MIN_EV" ] && ARGS+=( --min-ev "$MIN_EV" )
          if [ "${REQUIRE_ODDS,,}" = "true" ]; then ARGS+=( --require-odds ); fi
          if [ -n "$ODDS_BANDS" ]; then
            ARGS+=( --odds-bands "$ODDS_BANDS" )
          else
            [ -n "$ODDS_MIN" ] && ARGS+=( --odds-min "$ODDS_MIN" )
            [ -n "$ODDS_MAX" ] && ARGS+=( --odds-max "$ODDS_MAX" )
          fi
          if [ -n "$PARAMS_FILE" ]; then ARGS+=( --params "$PARAMS_FILE" ); fi

          echo "[debug] args: ${ARGS[*]}"
          python "$PYTHON_SCRIPT" "${ARGS[@]}" --outdir scripts/sims

      - name: Commit results into repo
        run: |
          set -eux
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add scripts/sims/*.csv scripts/sims/*.json || true
          git commit -m "SimS outputs ($(date +'%Y-%m-%d %H:%M:%S %Z'))" || true
          git push || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sims-outputs
          path: |
            scripts/sims/*.csv
            scripts/sims/*.json
          if-no-files-found: warn
