name: SimS Pipeline

on:
  workflow_dispatch:
    inputs:
      date:
        description: "YYYYMMDD（空=JSTの今日）"
        required: false
        default: ""
      pids:
        description: "場コード（例: 01,04,24）※カンマ区切り可"
        required: false
        default: ""
      races:
        description: "レース（例: 1R,2R）※カンマ区切り可"
        required: false
        default: ""
      sims:
        description: "試行回数（例: 600）"
        required: false
        default: "600"
      topn:
        description: "上位N（三連単）"
        required: false
        default: "18"
      unit:
        description: "1点あたり（円）"
        required: false
        default: "100"
      filters:
        description: "例: require_odds=true,min_ev=1.2,odds_bands=01-09,10-19"
        required: false
        default: ""
      keyman:
        description: "例: enable=true,thr=0.7,boost=0.15,aggr=0.0,buy_in_top3=false,buy_thr=0.7"
        required: false
        default: "enable=true,thr=0.7,boost=0.15,aggr=0.0,buy_in_top3=false,buy_thr=0.7"

jobs:
  pass3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pass3 for all PIDs
        run: |
          IFS=',' read -ra PID_ARR <<< "${{ inputs.pids }}"
          for PID in "${PID_ARR[@]:-01}"; do
            echo "Running for PID=$PID"
            gh workflow run wf_pass3_sims_integrated.yml \
              -f DATE="${{ inputs.date }}" \
              -f PID="$PID" \
              -f MODE="predict" \
              -f SIMS="${{ inputs.sims }}" \
              -f TOPN="${{ inputs.topn }}" \
              -f UNIT="${{ inputs.unit }}" \
              -f FILTERS="${{ inputs.filters }}" \
              -f KEYMAN="${{ inputs.keyman }}" \
              -f OUTDIR="scripts/sims"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
