name: SimS Pipeline

on:
  workflow_dispatch:
    inputs:
      DATE:
        description: "対象日付 (YYYYMMDD)"
        required: true
        type: string
      PID:
        description: "場コード（01〜24）"
        required: true
        type: string
      MODE:
        description: "モード（predict / eval）"
        required: true
        default: "predict"
        type: string
      SIMS:
        description: "試行回数"
        required: false
        default: "600"
        type: string
      TOPN:
        description: "三連単 TopN"
        required: false
        default: "18"
        type: string
      UNIT:
        description: "1点あたりの購入金額（円）"
        required: false
        default: "100"
        type: string
      FILTERS:
        description: "カンマ区切りの絞り込み（例: require_odds=true,min_ev=1.2）"
        required: false
        default: ""
        type: string
      KEYMAN:
        description: "キーマン指定（例: enable=true,thr=0.7,boost=0.15,aggr=0.0）"
        required: false
        default: "enable=true,thr=0.7,boost=0.15,aggr=0.0,buy_in_top3=false,buy_thr=0.7"
        type: string
      OUTDIR:
        description: "出力ディレクトリ"
        required: false
        default: "scripts/sims"
        type: string

jobs:
  pass3:
    uses: ./.github/workflows/wf_pass3_sims_integrated.yml
    with:
      DATE: ${{ inputs.DATE }}
      PID: ${{ inputs.PID }}
      MODE: ${{ inputs.MODE }}
      SIMS: ${{ inputs.SIMS }}
      TOPN: ${{ inputs.TOPN }}
      UNIT: ${{ inputs.UNIT }}
      OUTDIR: ${{ inputs.OUTDIR }}
      FILTERS: ${{ inputs.FILTERS }}
      KEYMAN: ${{ inputs.KEYMAN }}
