# .github/workflows/build-c-features.yml
name: Build TENKAI C features

on:
  workflow_dispatch:
    inputs:
      date:
        description: '対象日 (YYYYMMDD)'
        required: true
      pid:
        description: '場コード pid (例: 02)'
        required: true
      race:
        description: 'レース (例: 1R)'
        required: true

permissions:
  contents: write

concurrency:
  group: tenkai-c-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy python-dateutil

      # パッケージとしてTENKAIをimportできるように
      - name: Ensure TENKAI package
        run: |
          mkdir -p TENKAI
          test -f TENKAI/__init__.py || echo "" > TENKAI/__init__.py

      - name: Sanity check
        run: |
          test -f TENKAI/features_c.py || { echo "TENKAI/features_c.py がありません"; exit 1; }

      - name: Build C features
        shell: bash
        run: |
          set -eo pipefail
          echo ">>> 実行コマンド"
          echo "python TENKAI/features_c.py --date '${{ github.event.inputs.date }}' --pid '${{ github.event.inputs.pid }}' --race '${{ github.event.inputs.race }}'"
          python TENKAI/features_c.py \
            --date "${{ github.event.inputs.date }}" \
            --pid  "${{ github.event.inputs.pid }}" \
            --race "${{ github.event.inputs.race }}"

      - name: Commit outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TENKAI/features_c.csv || true
          git diff --cached --quiet || git commit -m "TENKAI C features: ${{ github.event.inputs.date }} pid=${{ github.event.inputs.pid }} race=${{ github.event.inputs.race }}"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tenkai-c-${{ github.event.inputs.date }}-${{ github.event.inputs.pid }}-${{ github.event.inputs.race }}
          path: TENKAI/features_c.csv
          if-no-files-found: warn
