name: TENKAI Predict

on:
  workflow_dispatch:
    inputs:
      date:
        description: "対象日 (YYYYMMDD)"
        required: true
      pid:
        description: "場コード pid (例: 02 / ALL)"
        required: true
      race:
        description: "レース (例: 1R) 空なら全R"
        required: false
        default: ""

permissions:
  contents: write

concurrency:
  group: predict-${{ github.ref }}
  cancel-in-progress: true

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pandas lightgbm scikit-learn joblib

      - name: Ensure TENKAI package
        run: |
          mkdir -p TENKAI
          [ -f TENKAI/__init__.py ] || printf "" > TENKAI/__init__.py

      - name: Run prediction (tansyo + kimarite)
        shell: bash
        env:
          DATE: ${{ github.event.inputs.date }}
          PID:  ${{ github.event.inputs.pid }}
          RACE: ${{ github.event.inputs.race }}
        run: |
          set -euo pipefail
          PYTHONPATH=.

          build_one() {
            local d="$1" p="$2" r="${3:-}"
            local r_opt=""
            if [ -n "$r" ]; then r_opt="--race $r"; fi
            echo ">>> run predict: $d $p $r_opt"
            PYTHONPATH="$PYTHONPATH" python TENKAI/predict.py \
              --date "$d" --pid "$p" $r_opt \
              --outdir predictions
          }

          if [ "${PID}" = "ALL" ]; then
            BASE="public/integrated/v1/${DATE}"
            if [ ! -d "$BASE" ]; then
              echo "No integrated data for ${DATE}"; exit 0
            fi
            for dir in "$BASE"/*; do
              [ -d "$dir" ] || continue
              p="$(basename "$dir")"
              build_one "${DATE}" "${p}" "${RACE}"
            done
          else
            build_one "${DATE}" "${PID}" "${RACE}"
          fi

      - name: List predictions
        run: |
          echo "---- generated predictions ----"
          ls -R predictions || true

      - name: Commit predictions
        shell: bash
        env:
          DATE: ${{ github.event.inputs.date }}
          PID:  ${{ github.event.inputs.pid }}
          RACE: ${{ github.event.inputs.race }}
        run: |
          set -euo pipefail
          FILES="$(find predictions/${DATE} -type f -name '*.csv' -print 2>/dev/null || true)"
          if [ -n "$FILES" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add $FILES
            git diff --cached --quiet || git commit -m "TENKAI predictions: ${DATE} pid=${PID} race=${RACE:-ALL}"
            set +e
            git push
            if [ $? -ne 0 ]; then
              set -e
              git fetch origin
              git pull --rebase origin "${GITHUB_REF_NAME}"
              git push
            fi
          else
            echo "No prediction CSV generated; skip commit."
          fi

      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: predictions-${{ github.event.inputs.date }}-${{ github.event.inputs.pid }}${{ github.event.inputs.race && format('-{0}', github.event.inputs.race) || '' }}
          path: predictions/${{ github.event.inputs.date }}/**/*.csv
          if-no-files-found: warn
