# -*- coding: utf-8 -*-
"""
CLI ラッパー（ワークフローからこれを叩く）
"""
import argparse
from TENKAI.features_c import build_c_features

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", required=True)
    ap.add_argument("--pid", required=True)
    ap.add_argument("--race", default="")
    args = ap.parse_args()
    build_c_features(args.date, args.pid, args.race)
