name: build-c-features

on:
  workflow_dispatch:
    inputs:
      date:
        description: "レース日付 (YYYYMMDD)"
        required: true
      pid:
        description: "場コード (例: 02)"
        required: true
      race:
        description: "レース番号 (例: 1R)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Sanity check
        run: |
          test -f TENKAI/features_c.py || { echo "TENKAI/features_c.py がありません"; exit 1; }

      - name: Ensure TENKAI package
        run: mkdir -p TENKAI

      - name: Build C features
        shell: bash
        run: |
          set -eo pipefail
          export PYTHONPATH="${PYTHONPATH:-}:$(pwd)"

          RACE_OPT=""
          if [ -n "${{ github.event.inputs.race }}" ]; then
            RACE_OPT="--race '${{ github.event.inputs.race }}'"
          fi

          echo ">>> 実行コマンド"
          echo "python TENKAI/build_c_features.py --date '${{ github.event.inputs.date }}' --pid '${{ github.event.inputs.pid }}' $RACE_OPT"

          python TENKAI/build_c_features.py \
            --date "${{ github.event.inputs.date }}" \
            --pid  "${{ github.event.inputs.pid }}" \
            ${RACE_OPT}
