name: Predict TENKAI win (ALL model)

on:
  workflow_dispatch:
    inputs:
      date:
        description: '対象日 (YYYYMMDD)'
        required: true
      pid:
        description: '場コード pid (空=全pid)'
        required: false
        default: ''
      race:
        description: 'レース (例: 1R) 空=all.csv優先→1R..12R探索'
        required: false
        default: ''
      model_date:
        description: '学習日 (LATEST=自動検出)'
        required: false
        default: 'LATEST'

permissions:
  contents: write

concurrency:
  group: tenkai-predict-${{ github.ref }}
  cancel-in-progress: true

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Ensure TENKAI package
        run: |
          mkdir -p TENKAI
          [ -f TENKAI/__init__.py ] || printf "" > TENKAI/__init__.py

      - name: Sanity check
        run: |
          test -f TENKAI/tenkai_predict_win.py || { echo "TENKAI/tenkai_predict_win.py がありません"; exit 1; }

      - name: Run prediction (ALL model)
        shell: bash
        run: |
          set -euo pipefail
          PID_OPT=""
          RACE_OPT=""
          if [ -n "${{ github.event.inputs.pid }}" ]; then
            PID_OPT="--pid ${{ github.event.inputs.pid }}"
          fi
          if [ -n "${{ github.event.inputs.race }}" ]; then
            RACE_OPT="--race ${{ github.event.inputs.race }}"
          fi
          echo ">>> 実行"
          echo python TENKAI/tenkai_predict_win.py --date ${{ github.event.inputs.date }} $PID_OPT $RACE_OPT --model_date ${{ github.event.inputs.model_date }}
          PYTHONPATH="." python TENKAI/tenkai_predict_win.py \
            --date ${{ github.event.inputs.date }} \
            $PID_OPT \
            $RACE_OPT \
            --model_date ${{ github.event.inputs.model_date }}

      - name: Commit predictions
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TENKAI/predictions/v1/** || true
          git diff --cached --quiet || git commit -m "TENKAI predictions: ${{ github.event.inputs.date }} pid=${{ github.event.inputs.pid }} race=${{ github.event.inputs.race }} model_date=${{ github.event.inputs.model_date }}"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tenkai-pred-${{ github.event.inputs.date }}${{ github.event.inputs.pid && format('-{0}', github.event.inputs.pid) || '' }}${{ github.event.inputs.race && format('-{0}', github.event.inputs.race) || '' }}
          path: TENKAI/predictions/v1/**
          if-no-files-found: warn
