name: Trigger Integrate and Publish

on:
  workflow_dispatch:
    inputs:
      date:
        description: "開催日 (YYYYMMDD or 'today')"
        required: true
        default: "today"
      pid:
        description: "場コード 01..24"
        required: true
        default: "04"
      race:
        description: "レース番号 1R..12R"
        required: true
        default: "1R"

permissions:
  actions: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch integrate-and-publish
        run: |
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/boat-satan/racecard-crawl-api/actions/workflows/180322421/dispatches \
            -d "$(jq -n \
                  --arg ref "main" \
                  --arg date "${{ github.event.inputs.date }}" \
                  --arg pid  "${{ github.event.inputs.pid }}" \
                  --arg race "${{ github.event.inputs.race }}" \
                  '{ref:$ref, inputs:{date:$date, pid:$pid, race:$race}}')"
      - name: Note
        run: echo "Dispatched integrate-and-publish with inputs: date=${{ github.event.inputs.date }} pid=${{ github.event.inputs.pid }} race=${{ github.event.inputs.race }}"
