name: Trigger Integrate and Publish

on:
  workflow_dispatch:
    inputs:
      date:
        description: "開催日 (YYYYMMDD or 'today')"
        required: true
        default: "today"
      pid:
        description: "場コード 01..24"
        required: true
        default: "04"
      race:
        description: "レース番号 1R..12R"
        required: true
        default: "1R"

permissions:
  actions: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Build dispatch payload
        shell: bash
        run: |
          cat > body.json <<'JSON'
          {
            "ref": "main",
            "inputs": {
              "date": "${{ github.event.inputs.date }}",
              "pid":  "${{ github.event.inputs.pid }}",
              "race": "${{ github.event.inputs.race }}"
            }
          }
          JSON
          echo "---- body.json ----"
          cat body.json

      - name: Dispatch integrate-and-publish
        shell: bash
        run: |
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/boat-satan/racecard-crawl-api/actions/workflows/180322421/dispatches \
            --data @body.json
          echo "Dispatched with inputs: date=${{ github.event.inputs.date }} pid=${{ github.event.inputs.pid }} race=${{ github.event.inputs.race }}"
