name: wf_pass3_sims_integrated

on:
  workflow_call:
    inputs:
      DATE:
        required: true
        type: string
      PID:
        required: true
        type: string
      MODE:
        required: true
        type: string
        default: "predict"
      SIMS:
        required: true
        type: string
        default: "600"
      TOPN:
        required: true
        type: string
        default: "18"
      UNIT:
        required: true
        type: string
        default: "100"
      FILTERS:
        required: false
        type: string
        default: ""
      KEYMAN:
        required: false
        type: string
        default: "enable=true,thr=0.7,boost=0.15,aggr=0.0,buy_in_top3=false,buy_thr=0.7"
      OUTDIR:
        required: true
        type: string
        default: "scripts/sims"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas joblib scikit-learn

      - name: Parse FILTERS & KEYMAN
        id: parse
        env:
          FILTERS: ${{ inputs.FILTERS }}
          KEYMAN: ${{ inputs.KEYMAN }}
        run: |
          set -euo pipefail
          parse_kvlist () {
            local s="$1"; local prefix="$2"
            IFS=',' read -r -a pairs <<< "$s"
            for kv in "${pairs[@]}"; do
              kv="$(echo "$kv" | xargs)"
              [ -z "$kv" ] && continue
              if [[ "$kv" == *"="* ]]; then
                k="$(echo "${kv%%=*}" | tr '[:lower:]' '[:upper:]' | tr -c 'A-Z0-9_' '_' | xargs)"
                v="$(echo "${kv#*=}" | xargs)"
                echo "$prefix$k=$v" >> "$GITHUB_OUTPUT"
              fi
            done
          }
          {
            echo "F_REQUIRE_ODDS=false"
            echo "F_MIN_EV=0"
            echo "F_ODDS_BANDS="
            echo "F_ODDS_MIN=0"
            echo "F_ODDS_MAX=0"
            echo "F_EXCLUDE_FIRST1=false"
            echo "F_ONLY_FIRST1=false"
            echo "F_BUY_IN_TOP3=false"
            echo "F_BUY_THR=0.7"
          } >> "$GITHUB_OUTPUT"
          {
            echo "K_ENABLE=true"
            echo "K_THR=0.7"
            echo "K_BOOST=0.15"
            echo "K_AGGR=0.0"
          } >> "$GITHUB_OUTPUT"
          [ -n "${FILTERS:-}" ] && parse_kvlist "$FILTERS" "F_"
          [ -n "${KEYMAN:-}" ] && parse_kvlist "$KEYMAN" "K_"

      - name: Run Pass3 (SimS integrated with ML)
        env:
          DATE: ${{ inputs.DATE }}
          PID: ${{ inputs.PID }}
          MODE: ${{ inputs.MODE }}
          SIMS: ${{ inputs.SIMS }}
          TOPN: ${{ inputs.TOPN }}
          OUTDIR: ${{ inputs.OUTDIR }}
          F_REQUIRE_ODDS: ${{ steps.parse.outputs.F_REQUIRE_ODDS }}
          F_MIN_EV: ${{ steps.parse.outputs.F_MIN_EV }}
          F_ODDS_BANDS: ${{ steps.parse.outputs.F_ODDS_BANDS }}
          F_ODDS_MIN: ${{ steps.parse.outputs.F_ODDS_MIN }}
          F_ODDS_MAX: ${{ steps.parse.outputs.F_ODDS_MAX }}
          F_EXCLUDE_FIRST1: ${{ steps.parse.outputs.F_EXCLUDE_FIRST1 }}
          F_ONLY_FIRST1: ${{ steps.parse.outputs.F_ONLY_FIRST1 }}
          F_BUY_IN_TOP3: ${{ steps.parse.outputs.F_BUY_IN_TOP3 }}
          F_BUY_THR: ${{ steps.parse.outputs.F_BUY_THR }}
          K_ENABLE: ${{ steps.parse.outputs.K_ENABLE }}
          K_THR: ${{ steps.parse.outputs.K_THR }}
          K_BOOST: ${{ steps.parse.outputs.K_BOOST }}
          K_AGGR: ${{ steps.parse.outputs.K_AGGR }}
        run: |
          set -euo pipefail
          echo "[pass3] MODE=$MODE DATE=$DATE PID=$PID"
          if [[ "${K_ENABLE,,}" == "false" ]]; then
            K_THR=9.9; K_BOOST=0; K_AGGR=0
          fi

          ARGS_COMMON="--base public --dates $DATE --pids $PID --sims $SIMS --topn $TOPN --keyman-threshold $K_THR --keyman-boost $K_BOOST --keyman-aggr $K_AGGR --ml-root TENKAI/predictions/v1 --outdir $OUTDIR"
          [[ "${F_EXCLUDE_FIRST1,,}" == "true" ]] && ARGS_COMMON="$ARGS_COMMON --exclude-first1"
          [[ "${F_ONLY_FIRST1,,}" == "true" ]] && ARGS_COMMON="$ARGS_COMMON --only-first1"
          [[ "${F_BUY_IN_TOP3,,}" == "true" ]] && ARGS_COMMON="$ARGS_COMMON --buy-if-keyman-in-top3 --buy-keyman-threshold $F_BUY_THR"

          if [[ "$MODE" == "predict" ]]; then
            python scripts/sims/sims_integrated.py $ARGS_COMMON --predict-only
          else
            ARGS_FILTER=""
            [[ -n "$F_ODDS_BANDS" ]] && ARGS_FILTER="$ARGS_FILTER --odds-bands \"$F_ODDS_BANDS\""
            [[ "$F_ODDS_MIN" != "0" ]] && ARGS_FILTER="$ARGS_FILTER --odds-min $F_ODDS_MIN"
            [[ "$F_ODDS_MAX" != "0" ]] && ARGS_FILTER="$ARGS_FILTER --odds-max $F_ODDS_MAX"
            [[ "${F_REQUIRE_ODDS,,}" == "true" ]] && ARGS_FILTER="$ARGS_FILTER --require-odds"
            [[ "$F_MIN_EV" != "0" ]] && ARGS_FILTER="$ARGS_FILTER --min-ev $F_MIN_EV"
            eval python scripts/sims/sims_integrated.py $ARGS_COMMON --odds-base public/odds/v1 $ARGS_FILTER
          fi

      - name: Aggregate & write overall.json
        env:
          DATE: ${{ inputs.DATE }}
          MODE: ${{ inputs.MODE }}
          UNIT: ${{ inputs.UNIT }}
          SIMS: ${{ inputs.SIMS }}
          TOPN: ${{ inputs.TOPN }}
          PID: ${{ inputs.PID }}
          OUTDIR: ${{ inputs.OUTDIR }}
        run: |
          set -euo pipefail
          python scripts/sims/aggregate_overall.py "$OUTDIR" "$DATE" "$MODE" "$UNIT" "$SIMS" "$TOPN" "$PID"

      - name: Commit results
        if: always()
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ inputs.OUTDIR }}/pass2 || true
          git commit -m "wf_pass3: write overall.json for ${{ inputs.DATE }} PID=${{ inputs.PID }}" || echo "nothing to commit"
          git pull --rebase
          git push || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wf_pass3_outputs_${{ inputs.DATE }}_${{ inputs.PID }}
          path: ${{ inputs.OUTDIR }}/pass2/**
